version: '3.7'
services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./src:/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 80:80